<?php 
return array (
  'package' => 'StatSocial',
  'tagline' => 'StatSocial Analytical Platform',
  'description' => 'Understand and target your social audience.',
  'image' => 'https://logo.clearbit.com/statsocial.com?s=128',
  'repo' => 'https://github.com/RapidSoftwareSolutions/Marketplace-StatSocial-package',
  'keywords' => 
  array (
    0 => 'API',
  ),
  'accounts' => 
  array (
    'domain' => 'statsocial.com',
    'credentials' => 
    array (
      0 => 'apiKey',
    ),
  ),
  'blocks' => 
  array (
    0 => 
    array (
      'name' => 'getReports',
      'description' => 'Output is ordered by Demographic and followed by Affinity information. For each data point the following metrics are provided value, count, mean, percentile, multiplicity and average. For Geographic, and Demographic data points an additional statistical_info metric will be present with information regarding statistical relevance.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'reportHash',
          'type' => 'String',
          'info' => 'Unique report hash.',
          'required' => true,
        ),
        2 => 
        array (
          'name' => 'baseline',
          'type' => 'Number',
          'info' => 'Default value will be \'world\'.',
          'required' => false,
        ),
        3 => 
        array (
          'name' => 'reportDate',
          'type' => 'Number',
          'info' => 'represents a Unix timestamp of when the report was generated. Default value will be the latest report generated. Date must be in the future.',
          'required' => false,
        ),
        4 => 
        array (
          'name' => 'sample',
          'type' => 'Number',
          'info' => 'Sample report indicator.',
          'required' => false,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    1 => 
    array (
      'name' => 'getSpecificReportDates',
      'description' => 'Get report dates available for a specific report.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'reportHash',
          'type' => 'String',
          'info' => 'Unique report hash.',
          'required' => true,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    2 => 
    array (
      'name' => 'getReportStatus',
      'description' => 'Returns a list of custom reports generated by user (report name to upload hash etc).',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'reportHash',
          'type' => 'String',
          'info' => 'Unique hash belonging to report.',
          'required' => true,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    3 => 
    array (
      'name' => 'createTwitterFollowerReport',
      'description' => 'This report uses the twitter followers as the audience. To create custom or tweet reports other methods must be used. Any report older than two days will be automatically regenerated upon create.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'twitterId',
          'type' => 'String',
          'info' => '(required if twitter_handle is not supplied) twitter_id must be sent with all client requests. Multiple handles are separated by commas.',
          'required' => false,
        ),
        2 => 
        array (
          'name' => 'twitterHandle',
          'type' => 'String',
          'info' => '(required if twitter_id is not supplied) twitter_handle must be sent with all client requests. Multiple ids are separated by commas.',
          'required' => false,
        ),
        3 => 
        array (
          'name' => 'genderFilter',
          'type' => 'Array',
          'info' => 'Filtering by gender options to be used when creating a filtered report. Format ["male"].',
          'required' => false,
        ),
        4 => 
        array (
          'name' => 'agesFilter',
          'type' => 'Array',
          'info' => 'Filtering by ages options to be used when creating a filtered report. Format ["18-24"].',
          'required' => false,
        ),
        5 => 
        array (
          'name' => 'countriesFilter',
          'type' => 'Array',
          'info' => 'Filtering by countries options to be used when creating a filtered report. Format ["usa"].',
          'required' => false,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    4 => 
    array (
      'name' => 'generateCustomReport',
      'description' => 'Used to create a custom report. This report treats the list of ids or handles as the audience (not their followers as in the twitter report). To create follower or tweet reports other methods must be used.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'reportName',
          'type' => 'String',
          'info' => 'Name of report.',
          'required' => true,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    5 => 
    array (
      'name' => 'insertCustomReport',
      'description' => 'Inserting twitter ids or handles into a custom report. This is used for custom reports only.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'uploadHash',
          'type' => 'String',
          'info' => 'Upload hash to be used for inserting handles.',
          'required' => true,
        ),
        2 => 
        array (
          'name' => 'ids',
          'type' => 'String',
          'info' => 'List of twitter ids, separated by commas, to be inserted into report. Ids must be enclosed with brackets ie. [177490485] or [177490485,23423434].',
          'required' => true,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    6 => 
    array (
      'name' => 'createCustomReport',
      'description' => 'Used to create a custom report. This report treats the list of ids or handles as the audience (not their followers as in the twitter report). To create follower or tweet reports other methods must be used.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'uploadHash',
          'type' => 'String',
          'info' => 'Name of report.',
          'required' => true,
        ),
        2 => 
        array (
          'name' => 'genderFilter',
          'type' => 'Array',
          'info' => 'Filtering by gender options to be used when creating a filtered report. Format ["male"].',
          'required' => false,
        ),
        3 => 
        array (
          'name' => 'agesFilter',
          'type' => 'Array',
          'info' => 'Filtering by ages options to be used when creating a filtered report. Format ["18-24"].',
          'required' => false,
        ),
        4 => 
        array (
          'name' => 'countriesFilter',
          'type' => 'Array',
          'info' => 'Filtering by countries options to be used when creating a filtered report. Format ["usa"].',
          'required' => false,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    7 => 
    array (
      'name' => 'createTweetReport',
      'description' => 'This report details the audience of the users who have tweeted content that matches what was provided in the keywords. To create custom or twitter reports other methods must be used.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
        1 => 
        array (
          'name' => 'reportName',
          'type' => 'String',
          'info' => 'Name of report.',
          'required' => true,
        ),
        2 => 
        array (
          'name' => 'startDate',
          'type' => 'String',
          'info' => 'A unix timestamp. start_date will be set to the previous midnight.',
          'required' => true,
        ),
        3 => 
        array (
          'name' => 'endDate',
          'type' => 'String',
          'info' => 'A unix timestamp. start_date will be set to the previous midnight.',
          'required' => true,
        ),
        4 => 
        array (
          'name' => 'terms',
          'type' => 'String',
          'info' => 'String or Array of JSON Objects. If you are tracking a single term, then the keyword itself is suffice otherwise, tracking multiple terms must be in JSON form. Which results in filtering tweets containing \'http://google.com\' OR \'#test\' AND \'test2\'. (NOTE) Make sure to URL encode the terms value for multiple terms.',
          'required' => true,
        ),
        5 => 
        array (
          'name' => 'genderFilter',
          'type' => 'Array',
          'info' => 'Filtering by gender options to be used when creating a filtered report. Format ["male"].',
          'required' => false,
        ),
        6 => 
        array (
          'name' => 'agesFilter',
          'type' => 'Array',
          'info' => 'Filtering by ages options to be used when creating a filtered report. Format ["18-24"].',
          'required' => false,
        ),
        7 => 
        array (
          'name' => 'countriesFilter',
          'type' => 'Array',
          'info' => 'Filtering by countries options to be used when creating a filtered report. Format ["usa"].',
          'required' => false,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
    8 => 
    array (
      'name' => 'getApplicationStatus',
      'description' => 'Remaining window and remaining count details, also returns reports that have been generated by this account.',
      'args' => 
      array (
        0 => 
        array (
          'name' => 'apiKey',
          'type' => 'credentials',
          'info' => 'API key.',
          'required' => true,
        ),
      ),
      'callbacks' => 
      array (
        0 => 
        array (
          'name' => 'error',
          'info' => 'Error',
        ),
        1 => 
        array (
          'name' => 'success',
          'info' => 'Success',
        ),
      ),
    ),
  ),
  'custom' => 
  array (
    'blocks' => 
    array (
      'getReports' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'reportHash' => 'reportHash',
          'baseline' => 'baseline',
          'reportDate' => 'reportDate',
          'sample' => 'sample',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'getSpecificReportDates' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'reportHash' => 'reportHash',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'getReportStatus' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'reportHash' => 'reportHash',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'createTwitterFollowerReport' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'twitterId' => 'twitterId',
          'twitterHandle' => 'twitterHandle',
          'genderFilter' => 'genderFilter',
          'agesFilter' => 'agesFilter',
          'countriesFilter' => 'countriesFilter',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'generateCustomReport' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'reportName' => 'reportName',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'insertCustomReport' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'uploadHash' => 'uploadHash',
          'ids' => 'ids',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'createCustomReport' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'uploadHash' => 'uploadHash',
          'genderFilter' => 'genderFilter',
          'agesFilter' => 'agesFilter',
          'countriesFilter' => 'countriesFilter',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'createTweetReport' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
          'reportName' => 'reportName',
          'startDate' => 'startDate',
          'endDate' => 'endDate',
          'terms' => 'terms',
          'genderFilter' => 'genderFilter',
          'agesFilter' => 'agesFilter',
          'countriesFilter' => 'countriesFilter',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
      'getApplicationStatus' => 
      array (
        'dictionary' => 
        array (
          'apiKey' => 'apiKey',
        ),
        'vendorUrl' => 'http://api.statsocial.com:80/api/',
        'method' => 'POST',
      ),
    ),
  ),
);